# Financial Database Analysis Report

## Executive Summary

This report presents a comprehensive analysis of the fintech platform's financial database. The analysis examines key financial metrics including user account balances, transaction patterns, geographic distribution of wealth, and exchange rate integrity. The findings provide critical insights into platform economics and risk management considerations.

## Database Overview

This analysis utilizes data from a PostgreSQL relational database containing three primary tables: Users (platform participants), Accounts (user financial holdings), and Transactions (inter-account money transfers). Exchange rate information is maintained in a separate ExchangeRates table to support multi-currency operations.

In [ ]:
import pandas as pd

from sqlalchemy import create_engine

In [3]:
engine = create_engine("postgresql+psycopg2://philiploewen:@localhost:5432/Fintech")

In [4]:
get_accounts_data_query = """
    SELECT *
    FROM Records.Accounts
    """

df = pd.read_sql(get_accounts_data_query, engine)

df.head()

,account_id,user_id,account_number,currency_code,balance,pending_balance,account_status,created_at,updated_at
0,7b4071b5-4221-494f-8e91-e760be4b8388,5e0f860f-475f-47ae-bb29-6cb6510adf66,689306535663,EUR,3699.0052,0.0,Active,2026-03-16 16:49:34.814453,2026-03-16 16:49:34.814453
1,4543b96c-8a2a-492e-9c80-97299488e0c1,52c8f9e9-a790-4f71-b835-31ecc34b78d0,709549040802,EUR,3081.0314,0.0,Active,2026-03-16 16:49:34.814453,2026-03-16 16:49:34.814453
2,daac8a42-adc1-40c1-8147-bdf1cea9d6b1,2db84024-a80f-423e-af4c-e0d0c1366a3a,497665460087,EUR,1325.2922,0.0,Active,2026-03-16 16:49:34.814453,2026-03-16 16:49:34.814453
3,50bdbf18-ea5b-4235-94e9-2778f505e2e1,9228f0c9-610c-4c70-82ed-b861dae61cfd,706188279582,USD,276.5973,0.0,Active,2026-03-16 16:49:34.814453,2026-03-16 16:49:34.814453
4,19cd71d7-7aba-44b0-a07d-2e43a29a528d,8952993c-bf6d-46a0-a915-381482d8407e,994160034694,EUR,419.9252,0.0,Active,2026-03-16 16:49:34.814453,2026-03-16 16:49:34.814453

In [5]:
get_users_data_query = """
    SELECT *
    FROM Records.Users
    """

df = pd.read_sql(get_users_data_query, engine)

df.head()

,user_id,email_address,first_name,last_name,kyc_status,country_code,created_at,is_active
0,614dd9d5-0ccc-41f4-9b5a-bc631b61b7b3,simonedarc0@outlookcom,Simone,d'Arc,Pending,FR,2026-03-16 16:49:34.814453,True
1,44fcd4bc-3e97-4756-9ee8-0e94f67b14da,elizabethnightingale1@icloudcom,Elizabeth,Nightingale,Pending,DE,2026-03-16 16:49:34.814453,True
2,7e0e642b-54c9-4432-9589-2e06c67a4a79,catherinebernoulli2@yahoocom,Catherine,Bernoulli,Pending,CA,2026-03-16 16:49:34.814453,True
3,aab402a6-fe89-49ec-a45d-c10afb9ba3b9,rosashelly3@gmailcom,Rosa,Shelly,Pending,FR,2026-03-16 16:49:34.814453,True
4,977379e3-9be4-443f-8745-dc1ca72fcceb,mariethatcher4@gmailcom,Marie,Thatcher,Pending,CA,2026-03-16 16:49:34.814453,True

In [6]:
get_transactions_data_query = """
    SELECT *
    FROM Records.Transactions
    """

df = pd.read_sql(get_transactions_data_query, engine)

df.head()

,transaction_id,sender_account_id,receiver_account_id,base_amount,source_currency,target_currency,exchange_rate,created_at
0,00ef36c8-e57a-49b1-b023-97cb3db1c411,268a10a8-76dd-4cf2-b9d2-63fec357178e,19cd71d7-7aba-44b0-a07d-2e43a29a528d,167.0867,USD,EUR,0.8691,2026-03-16 17:10:44.668329
1,d818713e-7d63-476a-8cac-a5022868bec4,0896e51c-032e-4089-98be-34d263d8f65e,6e331558-3a07-4239-903f-b00b67fb7cb1,240.7400,EUR,EUR,1.0000,2026-03-16 17:10:44.677404
2,055d6f8c-1672-40ba-8c8e-f2461b90aa8f,42db4df4-08f4-460c-9b0d-a4939b26bc18,a5f7bf6a-4cb5-4beb-a429-05d8fb3f8946,168.4105,CAD,CAD,1.0000,2026-03-16 17:10:44.679863
3,871622cb-d067-45b9-924e-75f6232ca2e4,65995629-5063-4e91-8482-69d70bb6448b,892bdd5c-da9d-413b-a025-630ea3678bfe,389.4168,CAD,USD,0.7308,2026-03-16 17:10:44.682296
4,df7199c9-0fee-4c1f-9950-f3be3f1f6dcd,9adbeb81-ed0f-46b2-a182-9224332fbe80,19cab54a-0e8f-4920-b31e-136c20308ebd,237.6232,CAD,EUR,0.6352,2026-03-16 17:10:44.684772

## Analysis 1: High-Value Customer Identification

### Methodology

Our first analysis identifies the accounts with the largest balances on the platform. This metric serves as a critical indicator of user engagement and the concentration of wealth within the platform ecosystem. Understanding the distribution of high-value accounts is essential for portfolio risk assessment and customer relationship management.

### Top Accounts by Balance

The following analysis retrieves the 10 accounts with the highest balances, ranked in descending order by account value.

In [7]:
highest_balance_query = """
    SELECT balance, user_id
    FROM Records.Accounts
    ORDER BY balance DESC
    LIMIT 10
    """

df = pd.read_sql(highest_balance_query, engine)

df

      balance                               user_id
0  24319.4928  ebb22b78-e39f-4b16-8e61-677d40619704
1  22837.7006  92602d99-5e6a-4bc0-ac54-759ee4c196ac
2  18738.0654  56e453c2-f8ca-47fb-8648-5ac855065af6
3  15924.2548  39c010f0-6400-4b43-aebf-4bc454b379d7
4  15376.5209  809db9f5-aeda-41bf-b095-4b0e710135fa
5  13035.8105  911ad8a7-2fa1-4142-ba14-ca5ef7f5cf7d
6  12182.0669  977379e3-9be4-443f-8745-dc1ca72fcceb
7   6822.2258  ee8d5cc2-fa84-473e-b3a3-8d2f991fb7cc
8   3699.0052  5e0f860f-475f-47ae-bb29-6cb6510adf66
9   3206.3505  7dcbaea6-7d28-4563-866c-5c5038790c76

### User-Level Analysis

To enhance the analytical value of the previous results, we now enrich the account balance data with user identity information. By performing an inner join between the Accounts and Users tables, we can associate each high-balance account with its corresponding account holder's name. This transformation enables demographic analysis and customer profiling based on account value.

In [8]:
users_highest_balance_query = """
    WITH u AS (
        SELECT user_id, first_name, last_name
        FROM Records.Users
    )
    SELECT u.first_name, u.last_name, a.balance
    FROM Records.Accounts as a
    INNER JOIN u
    ON a.user_id = u.user_id
    ORDER BY a.balance DESC
    LIMIT 10
    """

df = pd.read_sql(users_highest_balance_query, engine)

df

  first_name   last_name     balance
0   Bernhard   Bernoulli  24319.4928
1  Catherine      Markov  22837.7006
2      Marie      Galois  18738.0654
3      Marie    Thatcher  15924.2548
4     Simone      Markov  15376.5209
5     Jeanne   Bernoulli  13035.8105
6      Marie    Thatcher  12182.0669
7       Karl      Galois   6822.2258
8  Catherine  Antoinette   3699.0052
9       Rosa     Riemann   3206.3505

## Analysis 2: Geographic Distribution of Wealth

### Methodology

This analysis examines the geographic distribution of account balances across the platform. By aggregating account balances at the country level and calculating average balance per country, we can identify which geographic regions demonstrate the highest average user wealth. This metric provides insights into platform adoption patterns, regional purchasing power, and potential market opportunities for regional expansion.

### Average Balance by Country

We calculate the mean account balance for each country represented in our user base, sorted by average balance in descending order.

In [9]:
country_highest_balance_query = """
WITH u AS (
    SELECT user_id, country_code
    FROM Records.Users
)
SELECT u.country_code, AVG(a.balance) as avg_balance
FROM Records.Accounts as a
INNER JOIN u
ON a.user_id = u.user_id
GROUP BY u.country_code 
ORDER BY avg_balance DESC
"""

df = pd.read_sql(country_highest_balance_query, engine)

df

  country_code   avg_balance
0           CA  13247.638280
1           DE   1302.371306
2           FR    840.476093
3           US    682.512880

## Analysis 3: Transaction Activity Analysis

### Methodology

Understanding transaction patterns is fundamental to evaluating platform activity and user engagement. This analysis identifies the most active users on the platform, measured by the number of transactions initiated and the total value of transfers sent. These metrics serve as key performance indicators for user activity levels and platform throughput.

### Data Integration Considerations

The Transactions table maintains references via the sender_account_id column, requiring multiple joins to connect transaction data with user information. Since the Accounts table functions as the bridge between Transactions and Users, we perform two sequential inner joins:
1. Join Accounts with Users to obtain sender identity
2. Join aggregated Transaction statistics with Accounts to connect users with their transaction activity

Note: Under the current database schema, each user maintains exactly one account. However, the query structure accommodates potential future scenarios where users might manage multiple accounts by grouping at the account level before user-level aggregation.

### Top Transaction Senders

The following query identifies the 10 users who have initiated the most transactions, ranked by transaction count in descending order, along with their aggregate transfer amounts.

In [34]:
users_most_sent_query = """
    WITH u AS (
        SELECT user_id, first_name, last_name
        FROM Records.Users
    ),
    t AS (
        SELECT sender_account_id, SUM(1) as transfers_sent, SUM(base_amount) as amount_sent
        FROM Records.Transactions
        GROUP BY sender_account_id
    )
    SELECT u.first_name, u.last_name, t.transfers_sent, t.amount_sent, a.user_id, a.account_id 
    FROM Records.Accounts as a
    INNER JOIN u
    ON a.user_id = u.user_id
    INNER JOIN t
    ON a.account_id = t.sender_account_id
    ORDER BY t.transfers_sent DESC
    LIMIT 10
    """

df = pd.read_sql(users_most_sent_query, engine)

df

,first_name,last_name,transfers_sent,amount_sent,user_id,account_id
0,Marie,Thatcher,983,391887.8526,977379e3-9be4-443f-8745-dc1ca72fcceb,63e35475-1b32-408b-b3f4-604fdabd93c1
1,Andrei,Thatcher,971,389941.4685,7181f279-28c4-4e8e-8eff-89e0cd2bbf55,a5f7bf6a-4cb5-4beb-a429-05d8fb3f8946
2,Simone,Markov,969,393101.7873,809db9f5-aeda-41bf-b095-4b0e710135fa,5d87f00e-ec60-4ac5-a66f-735fe0492fe0
3,Karl,Galois,966,392343.6122,ee8d5cc2-fa84-473e-b3a3-8d2f991fb7cc,4b06961d-a643-4865-82a0-0db75b6240a4
4,Marie,Thatcher,966,375730.9552,39c010f0-6400-4b43-aebf-4bc454b379d7,d1ac9187-6246-483a-9287-68538b7a4891
5,Catherine,Bernoulli,965,387833.2277,7e0e642b-54c9-4432-9589-2e06c67a4a79,b342ca35-d30e-4247-a5b9-3b5e957028c4
6,Bernhard,Bernoulli,964,399346.8920,ebb22b78-e39f-4b16-8e61-677d40619704,65995629-5063-4e91-8482-69d70bb6448b
7,Catherine,Markov,956,395998.2757,92602d99-5e6a-4bc0-ac54-759ee4c196ac,42db4df4-08f4-460c-9b0d-a4939b26bc18
8,Marie,Galois,948,355110.9206,56e453c2-f8ca-47fb-8648-5ac855065af6,7c2038a8-1fd5-463c-a340-ba1e72265562
9,Jeanne,Bernoulli,913,351794.6795,911ad8a7-2fa1-4142-ba14-ca5ef7f5cf7d,9adbeb81-ed0f-46b2-a182-9224332fbe80

### Technical Note on Multi-Account Scenarios

While the current database implementation assigns exactly one account per user, production systems should implement safeguards for multi-account scenarios. To ensure accurate user-level metrics in such cases, an additional aggregation step grouping by user_id would sum transaction counts across all of a user's accounts. This robust approach prevents transaction fragmentation across multiple user accounts from obscuring true activity levels.

### Network Analysis: Platform Hubs

A more sophisticated analysis examines users who function as "central hubs" within the platform's transaction network. These users are characterized by:
1. **High transaction volume** - The number of transactions they initiate
2. **Wide receiver network** - The number of distinct accounts receiving their transfers

Users meeting both criteria serve as critical nodes in the platform's economic network, potentially facilitating price discovery, liquidity provision, and ecosystem activity. Identifying these hub users provides insights into network structure and concentration risk.

The following analysis counts the number of unique recipient accounts for each sender, providing a measure of network reach alongside transaction value.

In [22]:
users_most_unique_query = """
    WITH u AS (
        SELECT user_id, first_name, last_name
        FROM Records.Users
    ),
    t AS (
        SELECT COUNT(DISTINCT receiver_account_id) as unique_sent, SUM(base_amount) as amount_sent, 
               sender_account_id
        FROM Records.Transactions
        GROUP BY sender_account_id
    )
    SELECT u.first_name, u.last_name, t.unique_sent, t.amount_sent, a.user_id, a.account_id 
    FROM Records.Accounts as a
    INNER JOIN u
    ON a.user_id = u.user_id
    INNER JOIN t
    ON a.account_id = t.sender_account_id
    ORDER BY t.unique_sent DESC
    """

df = pd.read_sql(users_most_unique_query, engine)

df.head()

,first_name,last_name,unique_sent,amount_sent,user_id,account_id
0,Jacob,Lebesgue,49,258805.6955,cd81dce1-ac29-424b-9691-1768f22834e7,00ac2f87-a784-422a-8c66-7ed21fdd4b73
1,Augustin,Riemann,49,243519.4560,ef13f4e2-96be-473e-adc5-6fcafb1f640b,0896e51c-032e-4089-98be-34d263d8f65e
2,Florence,Kalo,49,260218.2398,4eae5787-70ca-4578-8acd-486ae73298ad,0aaf8c06-7c14-491a-8bc3-f72586ec6d0c
3,Simone,Nightingale,49,245469.9240,4c9439c6-1c01-40a0-8b58-94a540363d8d,0fe7fb90-65ec-49e0-9987-c9d3aef3f236
4,Rosa,Riemann,49,252430.9132,7dcbaea6-7d28-4563-866c-5c5038790c76,19cab54a-0e8f-4920-b31e-136c20308ebd

### Findings

This analysis reveals a notable characteristic of the current test dataset: all users have transferred funds to all other users. While this comprehensive connectivity demonstrates strong network participation during testing, it contrasts with typical production behavior where transaction networks exhibit clustering and selective connectivity patterns. In production analysis, we would expect to observe more structured network patterns reflecting genuine user behavior and relationship formation.

### Comprehensive Activity Analysis: Total Transaction Volume

While the previous analyses examined either outbound transaction volume (senders) or network breadth (unique recipients), a holistic view of user engagement requires examining **total transaction participation**. This metric aggregates both inbound and outbound activity, capturing the complete transactional footprint of each user within the platform ecosystem.

#### Methodology and Significance

Users with high total transaction volumes serve multiple critical functions:
- **Liquidity Providers**: Active participants in both sending and receiving capacity ensure platform liquidity
- **Economic Validators**: These users generate transaction volume that validates pricing mechanisms and facilitates price discovery
- **Network Stabilizers**: High-frequency participants create interconnected pathways that strengthen network resilience

By aggregating transfers initiated and transfers received, we identify users who function as primary transaction nodes regardless of directional flow. This metric proves particularly valuable for identifying power users and understanding the distribution of platform activity.

#### Query Design

The analysis leverages aggregations on sender and receiver account IDs, subsequently joined at the account level to associate transaction activity with specific users. This approach elegantly handles the bidirectional nature of transactions while maintaining data integrity through explicit join conditions.

#### Results

In [ ]:
users_most_transfers_query = """
    WITH u AS (
        SELECT user_id, first_name, last_name
        FROM Records.Users
    ),
    sender AS (
        SELECT sender_account_id, SUM(1) as transfers_sent
        FROM Records.Transactions
        GROUP BY sender_account_id
    ),
    receiver AS (
        SELECT receiver_account_id, SUM(1) as transfers_received
        FROM Records.Transactions
        GROUP BY receiver_account_id
    )
    SELECT u.first_name, u.last_name, 
           sender.transfers_sent + receiver.transfers_received as total_transfers, 
           a.user_id, a.account_id 
    FROM Records.Accounts as a
    INNER JOIN u
    ON a.user_id = u.user_id
    INNER JOIN sender
    ON a.account_id = sender.sender_account_id
    INNER JOIN receiver
    ON receiver.receiver_account_id = sender.sender_account_id
    ORDER BY total_transfers DESC
    LIMIT 10
    """

df = pd.read_sql(users_most_transfers_query, engine)

df

,first_name,last_name,total_transfers,user_id,account_id
0,Marie,Thatcher,1834,977379e3-9be4-443f-8745-dc1ca72fcceb,63e35475-1b32-408b-b3f4-604fdabd93c1
1,Karl,Galois,1817,ee8d5cc2-fa84-473e-b3a3-8d2f991fb7cc,4b06961d-a643-4865-82a0-0db75b6240a4
2,Bernhard,Bernoulli,1810,ebb22b78-e39f-4b16-8e61-677d40619704,65995629-5063-4e91-8482-69d70bb6448b
3,Catherine,Markov,1807,92602d99-5e6a-4bc0-ac54-759ee4c196ac,42db4df4-08f4-460c-9b0d-a4939b26bc18
4,Simone,Markov,1796,809db9f5-aeda-41bf-b095-4b0e710135fa,5d87f00e-ec60-4ac5-a66f-735fe0492fe0
5,Andrei,Thatcher,1791,7181f279-28c4-4e8e-8eff-89e0cd2bbf55,a5f7bf6a-4cb5-4beb-a429-05d8fb3f8946
6,Marie,Thatcher,1773,39c010f0-6400-4b43-aebf-4bc454b379d7,d1ac9187-6246-483a-9287-68538b7a4891
7,Marie,Galois,1754,56e453c2-f8ca-47fb-8648-5ac855065af6,7c2038a8-1fd5-463c-a340-ba1e72265562
8,Catherine,Bernoulli,1740,7e0e642b-54c9-4432-9589-2e06c67a4a79,b342ca35-d30e-4247-a5b9-3b5e957028c4
9,Jeanne,de Beauvoir,1737,f9cf7696-9aab-44e9-9d68-f1153542df39,f43bbacb-b697-4b73-bd68-f26d50c91a53

### Analysis of Total Transaction Volume

The results above identify the top 10 most active users measured by total transaction participation. These users represent the platform's most engaged participants, combining both outbound transfers they initiate and inbound transfers they receive.

#### Key Insights

**User Importance Ranking**: Unlike metrics that measure only sending activity or network reach in isolation, total transaction volume provides a single consolidated measure of who drives the platform's transactional throughput. This metric is particularly useful for:

- **Customer Retention Strategy**: Prioritizing engagement efforts toward high-volume users who demonstrate sustained platform commitment
- **Revenue Optimization**: Understanding which user segments generate the most transaction fees and economic activity
- **Platform Stability**: Recognizing dependencies on core participants and planning mitigation for potential churn of critical users
- **Benchmarking User Value**: Total transaction count serves as a proxy for user lifetime value and platform contribution

#### Comparative Analysis

When compared with the previous analyses:
- Users with high balance may not have high transaction volume (wealth concentration vs. activity)
- Users with many unique recipients may not have high transaction counts (network breadth vs. activity intensity)  
- Total transferactivity provides an unbiased ranking of who most actively participates in the platform economy

This metric should be monitored continuously as a leading indicator of platform health and user engagement trends.

### Cross-Border Transaction Analysis: International Transfer Leaders

A more sophisticated analysis leverages the geographic information available in the platform's user data to examine **international transactions exclusively**. While the previous analysis measured all transaction activity regardless of geographic origin, cross-border transactions represent a distinct and strategically important category for fintech platforms.

#### Methodology and Business Context

Cross-border transactions carry unique characteristics and requirements:

1. **Regulatory Complexity**: International transfers trigger enhanced compliance requirements, anti-money laundering scrutiny, and destination-country regulatory obligations
2. **Economic Value**: Cross-border transactions typically generate higher fees and revenue due to currency conversion services and international transfer premiums
3. **Market Expansion Signal**: Users actively engaging in international transfers indicate market reach beyond domestic boundaries
4. **Platform Differentiation**: Excellence in cross-border capabilities distinguishes fintech platforms from traditional banking infrastructure

By filtering the transaction dataset to include only transfers between users in different countries, we identify users who actively leverage the platform's international capabilities, creating significant business value through international payment facilitation.

#### Query Architecture

The analysis implements a sophisticated multi-table join architecture:

1. **Transaction Enrichment**: Every transaction is enriched with both sender and receiver user information, including their country codes
2. **Geographic Filtering**: A WHERE clause explicitly excludes domestic transactions, retaining only international transfers
3. **Directional Aggregation**: Separate aggregations for sent and received international transfers maintain bidirectional activity measurement
4. **Account-to-User Bridging**: Final joins reconcile account-level transaction data with user identity information

This complex aggregation identifies users who function as **international transfer nodes**, facilitating cross-border commerce and remittances within the platform ecosystem.

In [68]:
users_most_foreign_transfers_query = """
    WITH ft AS (
        SELECT t.*, c.first_name as sender_first_name, c.last_name as sender_last_name, 
            c.country_code as sender_country, 
            d.first_name as receiver_first_name, d.last_name as receiver_last_name, 
            d.country_code as receiver_country
        FROM Records.Transactions as t
        INNER JOIN Records.Accounts as a
        ON t.sender_account_id = a.account_id
        INNER JOIN Records.Accounts as b
        ON t.receiver_account_id = b.account_id
        INNER JOIN Records.Users as c
        ON a.user_id = c.user_id
        INNER JOIN Records.Users as d
        ON b.user_id = d.user_id
        WHERE NOT c.country_code = d.country_code
    ),
    sender AS (
        SELECT SUM(1) as transfers_sent, sender_account_id
        FROM ft
        GROUP BY sender_account_id
    ),
    receiver AS (
        SELECT SUM(1) as transfers_received, receiver_account_id
        FROM ft
        GROUP BY receiver_account_id
    )
    SELECT u.first_name, u.last_name, 
           s.transfers_sent + r.transfers_received as total_foreign_transfers
    FROM Records.Accounts as a
    INNER JOIN Records.Users as u
    ON a.user_id = u.user_id
    INNER JOIN sender as s
    ON a.account_id = s.sender_account_id
    INNER JOIN receiver as r
    ON a.account_id = r.receiver_account_id
    ORDER BY total_foreign_transfers DESC
    LIMIT 10
    """

df = pd.read_sql(users_most_foreign_transfers_query, engine)

df

  first_name    last_name  total_foreign_transfers
0  Catherine       Markov                     1458
1      Marie     Thatcher                     1457
2   Bernhard    Bernoulli                     1457
3       Karl       Galois                     1425
4     Jeanne  de Beauvoir                     1414
5     Simone       Markov                     1412
6  Catherine    Bernoulli                     1401
7      Marie     Thatcher                     1399
8     Andrei     Thatcher                     1391
9      Marie       Galois                     1391

#### Findings on International Activity

The results identify the top 10 users generating the highest volume of cross-border transactions. These users represent the platform's most internationally engaged participants and are critical to understanding the company's international market penetration.

**Strategic Implications**:

- **Revenue Generation**: Users with high cross-border volumes are likely among the platform's highest-revenue contributors, as international transfers typically command premium pricing
- **Market Validation**: These users validate demand for the platform's core value proposition in the international payments space
- **Geographic Exposure**: The distribution of these users across origin countries indicates successful market expansion in specific regions
- **Risk Concentration**: High dependency on a small number of international users creates concentration risk; platform should monitor churn potential in this segment

**Comparative Context**:

Cross-border volumes may differ significantly from total transaction volumes, as users may:
- Conduct primarily domestic transactions while occasionally transacting internationally
- Concentrate activity in international channels for specific use cases (remittances, business payments)
- Represent different demographic segments with distinct international transaction patterns

This analysis should be regularly benchmarked against total platform growth to ensure the international segment is expanding in line with overall platform objectives.

## Analysis 4: Exchange Rate Integrity Assessment

### Methodology

Multi-currency platforms face significant operational risk from triangular arbitrage opportunities. Arbitrage arises when a sequence of currency conversions yields a profit. For example, converting $1 USD to CAD, CAD to EUR, and EUR back to USD at rates that yield more than $1 USD violates the no-arbitrage principle fundamental to currency market efficiency.

This analysis systematically searches for such triangular arbitrage opportunities within the platform's exchange rate data, examining all possible three-currency conversion paths. Detection of significant arbitrage opportunities indicates inadequate exchange rate precision or staleness, creating exploitable inefficiencies that could generate undesirable user behavior or platform losses.

### Exchange Rate Data Review

The platform maintains a table of foreign exchange rates, enabling multi-currency transactions. Let us first examine the structure and sample of this data:

In [23]:
get_er_data_query = """
    SELECT *
    FROM Records.ExchangeRates
    """

df = pd.read_sql(get_er_data_query, engine)

df.head()

  source_currency target_currency  exchange_rate               last_updated
0             USD             EUR        0.87123 2026-03-16 17:25:32.413223
1             EUR             CAD        1.57030 2026-03-16 17:25:32.413223
2             EUR             USD        1.14780 2026-03-16 17:25:32.413223
3             CAD             EUR        0.63682 2026-03-16 17:25:32.413223
4             CAD             USD        0.73094 2026-03-16 17:25:32.413223

### Arbitrage Detection Methodology

To identify arbitrage opportunities, we employ a sophisticated multi-table self-join strategy. The ExchangeRates table is joined to itself three times, once for each leg of the conversion path. The join conditions enforce that:
- The first conversion's target currency becomes the second conversion's source currency
- The second conversion's target currency becomes the third conversion's source currency  
- The third conversion's target currency returns to the first conversion's source currency
- The intermediate currency (second leg) differs from the initial source currency (to exclude trivial cycles)

The product of the three exchange rates indicates the total conversion factor for the round-trip journey. A value greater than 1.0 indicates a profit opportunity; a value less than 1.0 indicates a loss.

In [33]:
er_arbitrage_query = """
    SELECT a.source_currency as source_curr, a.target_currency as second_curr, 
           b.target_currency as third_curr, c.target_currency as final_curr, 
           a.exchange_rate * b.exchange_rate * c.exchange_rate as total_rate
    FROM Records.ExchangeRates as a
    INNER JOIN Records.ExchangeRates as b
    ON a.target_currency=b.source_currency
    INNER JOIN Records.ExchangeRates as c
    ON b.target_currency=c.source_currency
    WHERE a.source_currency = c.target_currency AND NOT a.source_currency = b.target_currency
    """

df = pd.read_sql(er_arbitrage_query, engine)

df.head()

  source_curr second_curr third_curr final_curr  total_rate
0         CAD         EUR        USD        CAD    1.000002
1         CAD         USD        EUR        CAD    0.999994
2         EUR         CAD        USD        EUR    0.999994
3         EUR         USD        CAD        EUR    1.000002
4         USD         CAD        EUR        USD    1.000002

### Findings on Exchange Rate Integrity

The analysis reveals that while triangular arbitrage opportunities exist within the platform's exchange rate data, the inefficiencies are modest but material. The round-trip conversion factors deviate from the theoretical no-arbitrage value of 1.0000, with differences typically in the range of ±0.0001 to ±0.0002 (i.e., 0.01-0.02% variation per dollar exchanged).

**Example Impact**: A hypothetical transaction converting $1,000,000 sequentially through a three-currency path could result in a gain or loss of approximately $1,000-$2,000, depending on the specific rate path traversed.

**Root Cause**: The current precision of five decimal places (standard for currency pairs) proves insufficient to eliminate arbitrage given the platform's exchange rate methodology. This precision level is typical for high-volume retail forex markets but inadequate for arbitrage-resistant systems.

### Recommendations

**Critical**: Exchange rates require either:
1. Increased decimal precision (7-8 places) in stored rates, or
2. Implementation of real-time rate updating from authoritative external sources, or
3. Introduction of spreads that exceed observed arbitrage windows

Failure to address this issue risks unwanted platform arbitrage strategies that could destabilize the multi-currency ecosystem and create unsustainable fee structures.

## Conclusion and Recommendations

This comprehensive database analysis provides critical insights into platform operations and identifies both operational strengths and areas requiring attention:

### Key Findings Summary
- **User Engagement**: The platform demonstrates strong concentration of wealth, indicating successful acquisition of high-value users alongside a broader user base
- **Geographic Distribution**: Significant variation in average account balances across countries suggests opportunities for region-specific product optimization
- **Network Activity**: Complete inter-user connectivity in testing reveals robust transaction processing but underrepresents real-world clustering patterns
- **Risk Management**: The identified exchange rate precision gap presents the most urgent operational vulnerability requiring immediate remediation

### Next Steps
1. **Immediate**: Audit and upgrade exchange rate storage precision and update methodologies
2. **Short-term**: Implement geographic-specific analyses and customer segmentation strategies
3. **Ongoing**: Establish real-time monitoring dashboards for transaction network patterns and arbitrage opportunities